INFO 2025-03-14 15:39:15,283 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 15:41:22,102 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 15:41:22,521 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 15:41:56,994 views === Registration Request Started ===
INFO 2025-03-14 15:41:56,994 views Raw request data: {'mobile_number': '8474743393', 'surname': 'u3u383883', 'given_name': 'u4u44u4', 'password': '339344U4'}
INFO 2025-03-14 15:41:56,995 views Processed data after case conversion: {'mobile_number': '8474743393', 'surname': 'U3U383883', 'given_name': 'U4U44U4', 'password': '339344U4'}
INFO 2025-03-14 15:41:57,881 views User registered successfully with ID: 20
INFO 2025-03-14 15:42:50,546 views === Registration Request Started ===
INFO 2025-03-14 15:42:50,547 views Raw request data: {'mobile_number': '6774474881', 'surname': 'jfjfhhf', 'given_name': 'hfhfhf', 'password': '4881HFHF'}
INFO 2025-03-14 15:42:50,547 views Processed data after case conversion: {'mobile_number': '6774474881', 'surname': 'JFJFHHF', 'given_name': 'HFHFHF', 'password': '4881HFHF'}
INFO 2025-03-14 15:42:51,437 views User registered successfully with ID: 21
INFO 2025-03-14 15:43:59,884 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 15:44:00,253 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 15:45:23,554 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 15:45:23,899 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 15:46:01,938 views Processed data after case conversion: {'mobile_number': '7737393939', 'surname': 'HDNDNND', 'given_name': 'EYEYYE', 'password': '3939EYYE'}
INFO 2025-03-14 15:46:02,826 views User registered successfully with ID: 22
INFO 2025-03-14 15:50:08,032 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/models.py changed, reloading.
INFO 2025-03-14 15:50:08,367 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 15:54:18,270 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 15:54:21,284 views Processed data after case conversion: {'mobile_number': '7373838921', 'surname': 'IMTHER', 'given_name': 'EVERYEHR', 'password': '8921YEHR'}
INFO 2025-03-14 15:54:22,235 views User registered successfully with ID: 23
INFO 2025-03-14 15:56:31,240 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 15:56:31,588 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:13:15,131 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:17:03,151 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/models.py changed, reloading.
INFO 2025-03-14 17:17:03,486 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:20:47,374 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 17:20:47,692 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:21:07,123 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 17:21:07,427 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:21:15,704 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 17:21:16,062 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:22:27,063 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 17:22:27,352 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:22:29,560 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 17:22:29,856 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:23:05,447 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/urls.py changed, reloading.
INFO 2025-03-14 17:23:05,827 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:23:24,224 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/urls.py changed, reloading.
INFO 2025-03-14 17:23:24,510 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:25:04,985 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:25:24,375 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 17:25:24,685 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:25:25,090 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 17:25:25,452 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:27:22,354 views User signed up successfully with ID: 24
INFO 2025-03-14 17:50:57,035 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 17:50:57,337 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:51:14,767 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 17:51:15,101 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:51:24,482 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 17:51:24,779 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:51:42,200 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 17:51:42,490 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:52:07,036 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 17:52:07,342 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:52:41,966 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 17:52:42,284 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:53:03,809 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/urls.py changed, reloading.
INFO 2025-03-14 17:53:04,127 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:54:41,359 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/urls.py changed, reloading.
INFO 2025-03-14 17:54:41,709 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:57:46,231 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/models.py changed, reloading.
INFO 2025-03-14 17:57:46,544 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 17:58:33,342 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/models.py changed, reloading.
INFO 2025-03-14 17:58:33,655 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 18:01:35,018 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 18:01:35,352 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 18:06:24,199 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 18:06:24,524 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 18:06:35,896 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 18:06:36,234 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 18:07:47,226 views User signed up successfully with ID: 25
ERROR 2025-03-14 18:08:10,983 views Signup validation failed: {'mobile_number': [ErrorDetail(string='user sign up with this mobile number already exists.', code='unique')], 'given_name': [ErrorDetail(string='This field is required.', code='required')], 'password': [ErrorDetail(string='This field is required.', code='required')]}
WARNING 2025-03-14 18:08:10,983 log Bad Request: /api/signup/
INFO 2025-03-14 18:22:03,936 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 18:44:59,876 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 18:45:00,223 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 18:45:09,609 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/urls.py changed, reloading.
INFO 2025-03-14 18:45:09,896 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 18:51:57,579 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/urls.py changed, reloading.
INFO 2025-03-14 18:51:57,879 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 18:52:05,153 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-14 18:52:05,469 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 18:52:11,739 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/models.py changed, reloading.
INFO 2025-03-14 18:52:12,061 autoreload Watching for file changes with StatReloader
INFO 2025-03-14 20:42:30,741 views User signed up successfully with ID: 26
WARNING 2025-03-14 20:42:46,000 log Unauthorized: /api/login/
WARNING 2025-03-14 21:00:20,626 log Unauthorized: /api/login/
INFO 2025-03-14 23:38:42,147 views User signed up successfully with ID: 27
WARNING 2025-03-14 23:42:17,911 log Unauthorized: /api/login/
WARNING 2025-03-14 23:42:40,247 log Unauthorized: /api/login/
INFO 2025-03-15 10:44:27,114 autoreload Watching for file changes with StatReloader
WARNING 2025-03-15 10:44:33,725 log Not Found: /favicon.ico
ERROR 2025-03-15 10:48:02,485 views Signup validation failed: {'mobile_number': [ErrorDetail(string='user sign up with this mobile number already exists.', code='unique')]}
WARNING 2025-03-15 10:48:02,486 log Bad Request: /api/signup/
INFO 2025-03-15 10:49:57,069 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 10:50:39,100 autoreload /home/ajay/Documents/yuvachetana-app/backend/backend/settings.py changed, reloading.
INFO 2025-03-15 10:50:39,573 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 10:50:43,345 autoreload Watching for file changes with StatReloader
ERROR 2025-03-15 10:51:47,584 views Signup validation failed: {'mobile_number': [ErrorDetail(string='user sign up with this mobile number already exists.', code='unique')]}
WARNING 2025-03-15 10:51:47,585 log Bad Request: /api/signup/
ERROR 2025-03-15 10:53:00,222 log Internal Server Error: /api/signup/
Traceback (most recent call last):
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "yuva-chetana.cn24g08aomsm.ap-south-1.rds.amazonaws.com" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/api/views.py", line 86, in signup
    if serializer.is_valid():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 499, in to_internal_value
    validated_value = field.run_validation(primitive_value)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/rest_framework/fields.py", line 757, in run_validation
    return super().run_validation(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/rest_framework/fields.py", line 539, in run_validation
    self.run_validators(value)
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/rest_framework/fields.py", line 551, in run_validators
    validator(value, self)
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/rest_framework/validators.py", line 73, in __call__
    if qs_exists(queryset):
       ^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/rest_framework/validators.py", line 21, in qs_exists
    return queryset.exists()
           ^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 660, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1542, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 320, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 296, in _cursor
    self.ensure_connection()
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: could not translate host name "yuva-chetana.cn24g08aomsm.ap-south-1.rds.amazonaws.com" to address: Temporary failure in name resolution

INFO 2025-03-15 10:53:38,929 autoreload /home/ajay/Documents/yuvachetana-app/backend/backend/settings.py changed, reloading.
INFO 2025-03-15 10:53:39,419 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 10:54:17,227 autoreload Watching for file changes with StatReloader
ERROR 2025-03-15 10:54:21,524 exception Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-03-15 10:54:21,596 log Bad Request: /
ERROR 2025-03-15 10:55:32,241 exception Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-03-15 10:55:32,282 log Bad Request: /
INFO 2025-03-15 10:55:39,470 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 11:03:08,160 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 11:03:21,873 views User signed up successfully with ID: 31
WARNING 2025-03-15 13:02:13,542 log Not Found: /api/user-details/
WARNING 2025-03-15 13:02:27,251 log Not Found: /api/user-details/
WARNING 2025-03-15 13:02:27,299 log Not Found: /api/user-details/
WARNING 2025-03-15 13:02:35,132 log Not Found: /api/user-details/
WARNING 2025-03-15 13:02:35,180 log Not Found: /api/user-details/
INFO 2025-03-15 13:16:58,637 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/models.py changed, reloading.
INFO 2025-03-15 13:17:01,270 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 13:17:06,043 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-15 13:17:08,467 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 13:17:11,925 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/urls.py changed, reloading.
INFO 2025-03-15 13:17:14,335 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 13:24:20,022 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-15 13:24:22,398 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 13:51:24,313 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/models.py changed, reloading.
INFO 2025-03-15 13:51:24,822 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 13:51:38,277 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-15 13:51:38,655 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 13:52:13,289 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-15 13:52:13,647 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 14:30:26,034 autoreload Watching for file changes with StatReloader
WARNING 2025-03-15 14:49:37,008 log Unauthorized: /api/login/
INFO 2025-03-15 16:31:16,187 autoreload Watching for file changes with StatReloader
ERROR 2025-03-15 16:31:19,729 exception Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-03-15 16:31:19,745 log Bad Request: /
INFO 2025-03-15 16:32:14,115 autoreload Watching for file changes with StatReloader
ERROR 2025-03-15 16:32:20,053 exception Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2025-03-15 16:32:20,070 log Bad Request: /
INFO 2025-03-15 16:39:50,357 autoreload Watching for file changes with StatReloader
WARNING 2025-03-15 16:39:55,063 log Not Found: /favicon.ico
INFO 2025-03-15 16:46:26,212 views Raw request data: {'mobile_number': '8431848402', 'full_name': 'AHDGD DYYY4Y4', 'date_of_birth': '2025-02-24', 'gender': 'male', 'caste_category': 'obc', 'state': 36, 'district': 19, 'mandal': 194, 'village': 5117}
INFO 2025-03-15 16:46:26,212 views Processed data: {'mobile_number': '8431848402', 'surname': None, 'given_name': None, 'password': None}
ERROR 2025-03-15 16:46:26,347 log Internal Server Error: /api/register/
Traceback (most recent call last):
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajay/Documents/yuvachetana-app/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'NoneType'>`
INFO 2025-03-15 17:01:26,781 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/models.py changed, reloading.
INFO 2025-03-15 17:01:27,267 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 17:01:48,789 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/serializers.py changed, reloading.
INFO 2025-03-15 17:01:49,139 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 17:02:17,761 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-15 17:02:18,069 autoreload Watching for file changes with StatReloader
WARNING 2025-03-15 17:04:13,224 log Bad Request: /api/register/
INFO 2025-03-15 17:09:24,464 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/models.py changed, reloading.
INFO 2025-03-15 17:09:24,847 autoreload Watching for file changes with StatReloader
WARNING 2025-03-15 17:10:42,245 log Bad Request: /api/register/
ERROR 2025-03-15 17:28:41,924 views Registration error: null value in column "user_id" of relation "registrations" violates not-null constraint
DETAIL:  Failing row contains (1, 8431848402, TEST USER, 1990-01-01, male, general, 2025-03-15 11:58:41.822101+00, f, 17, 1718, 36, 1, null).

ERROR 2025-03-15 17:28:41,925 log Internal Server Error: /api/register/
INFO 2025-03-15 17:34:10,235 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-15 17:34:10,583 autoreload Watching for file changes with StatReloader
ERROR 2025-03-15 17:35:23,231 views Registration error: null value in column "user_id" of relation "registrations" violates not-null constraint
DETAIL:  Failing row contains (2, 8431848402, TEST USER, 1990-01-01, male, general, 2025-03-15 12:05:23.130212+00, f, 17, 1718, 36, 1, null).

ERROR 2025-03-15 17:35:23,233 log Internal Server Error: /api/register/
INFO 2025-03-15 17:36:50,601 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/serializers.py changed, reloading.
INFO 2025-03-15 17:36:50,966 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 17:37:00,328 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/views.py changed, reloading.
INFO 2025-03-15 17:37:00,686 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 17:41:19,902 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/models.py changed, reloading.
INFO 2025-03-15 17:41:20,232 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 17:41:23,496 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/models.py changed, reloading.
INFO 2025-03-15 17:41:23,824 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 17:41:38,249 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/models.py changed, reloading.
INFO 2025-03-15 17:41:38,618 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 17:41:43,957 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/models.py changed, reloading.
INFO 2025-03-15 17:41:44,401 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 17:46:06,172 views User signed up successfully with ID: 33
INFO 2025-03-15 17:53:23,042 autoreload /home/ajay/Documents/yuvachetana-app/backend/api/models.py changed, reloading.
INFO 2025-03-15 17:53:23,405 autoreload Watching for file changes with StatReloader
INFO 2025-03-15 17:54:35,505 views User signed up successfully with ID: 34
INFO 2025-03-15 18:08:05,484 autoreload /home/ajay/Documents/yuvachetana-app/backend/backend/settings.py changed, reloading.
INFO 2025-03-15 18:08:05,816 autoreload Watching for file changes with StatReloader
